# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: safemode 1.3.6 ruby lib

Gem::Specification.new do |s|
  s.name = "safemode".freeze
  s.version = "1.3.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Sven Fuchs".freeze, "Peter Cooper".freeze, "Matthias Viehweger".freeze, "Kingsley Hendrickse".freeze, "Ohad Levy".freeze, "Dmitri Dolguikh".freeze]
  s.date = "2020-08-31"
  s.description = "A library for safe evaluation of Ruby code based on RubyParser and Ruby2Ruby. Provides Rails ActionView template handlers for ERB and Haml.".freeze
  s.email = "ohadlevy@gmail.com".freeze
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "LICENCSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "demo.rb",
    "init.rb",
    "lib/action_view/template_handlers/safe_erb.rb",
    "lib/action_view/template_handlers/safe_haml.rb",
    "lib/action_view/template_handlers/safemode_handler.rb",
    "lib/haml/safemode.rb",
    "lib/ruby_parser_string_io_patch.diff",
    "lib/rubyparser_bug.rb",
    "lib/safemode.rb",
    "lib/safemode/blankslate.rb",
    "lib/safemode/core_ext.rb",
    "lib/safemode/core_jails.rb",
    "lib/safemode/exceptions.rb",
    "lib/safemode/jail.rb",
    "lib/safemode/parser.rb",
    "lib/safemode/scope.rb",
    "safemode.gemspec",
    "test/test_erb_eval.rb",
    "test/test_helper.rb",
    "test/test_jail.rb",
    "test/test_safemode_eval.rb",
    "test/test_safemode_parser.rb"
  ]
  s.homepage = "http://github.com/svenfuchs/safemode".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.6".freeze
  s.summary = "A library for safe evaluation of Ruby code based on ParseTree/RubyParser and Ruby2Ruby".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby2ruby>.freeze, [">= 2.4.0"])
      s.add_runtime_dependency(%q<ruby_parser>.freeze, [">= 3.10.1"])
      s.add_runtime_dependency(%q<sexp_processor>.freeze, [">= 4.10.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_development_dependency(%q<rake>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<test-unit>.freeze, [">= 0"])
    else
      s.add_dependency(%q<ruby2ruby>.freeze, [">= 2.4.0"])
      s.add_dependency(%q<ruby_parser>.freeze, [">= 3.10.1"])
      s.add_dependency(%q<sexp_processor>.freeze, [">= 4.10.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
      s.add_dependency(%q<rake>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<test-unit>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<ruby2ruby>.freeze, [">= 2.4.0"])
    s.add_dependency(%q<ruby_parser>.freeze, [">= 3.10.1"])
    s.add_dependency(%q<sexp_processor>.freeze, [">= 4.10.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    s.add_dependency(%q<rake>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<test-unit>.freeze, [">= 0"])
  end
end

